# в этом файле описывается настройка подключения к базе данных
# в базе храняться не только данные о файлах пользователей, но и авторизационные данные пользователей.
# первичное наполнение базы происходит при инициализации docker-контейнера через файл настроек Dockerfile
# поэтому используется настройка ddl-auto: none для hibernate
spring:
  application:
    name: diploma
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
    port: 8080



